name: Build Windows Release

on:
  push:
    tags:
      - 'v*'  # Dispara quando fizer push de uma tag como v1.0.0
  workflow_dispatch:  # Permite execução manual

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --clean RiverCleanup.spec
    
    - name: List build contents
      run: |
        dir dist\RiverCleanup
    
    - name: Create ZIP archive
      run: |
        Compress-Archive -Path dist\RiverCleanup\* -DestinationPath RiverCleanup-Windows-${{ github.ref_name }}.zip
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: RiverCleanup-Windows
        path: RiverCleanup-Windows-${{ github.ref_name }}.zip
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: RiverCleanup-Windows-${{ github.ref_name }}.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --clean RiverCleanup.spec
    
    - name: Create TAR archive
      run: |
        cd dist
        tar -czf RiverCleanup-Linux-${{ github.ref_name }}.tar.gz RiverCleanup/
        mv RiverCleanup-Linux-${{ github.ref_name }}.tar.gz ..
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: RiverCleanup-Linux
        path: RiverCleanup-Linux-${{ github.ref_name }}.tar.gz
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: RiverCleanup-Linux-${{ github.ref_name }}.tar.gz
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
